### ISSUE TITLE
Dummy prove Docs / HTML Structure more explanation [Feature Request]: 

### ISSUE THREAD

**Issue by bananenbiegerei** [hirasso/scrollmirror#13]
### Describe the problem 🧐

After installing scrollmirror and importing in without any issues I am a bit lost on how to go further on. I miss a HTML Markup example, maybe with CSS classes, just to copy and have a static example.

I had to inspect the example to see the markup. But still problems to get it running.

### Describe the propsed solution 😎

Provide some Markup after the npm process in the readme

### Alternatives considered 🤔

Maybe even a codepen or the like?

### How important is this feature to you? 🧭

Nice to have

### Checked all these? 📚

- [X] I have read the [usage instructions](https://github.com/hirasso/scrollmirror#usage)
- [X] I have checked [discussions](https://github.com/hirasso/scrollmirror/discussions) and [existing issues](https://github.com/issues?q=is%3Aissue+repo%3Ahirasso%2Fscrollmirror+) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/hirasso/scrollmirror/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by hirasso** [comment]
@bananenbiegerei added some more info to the README: https://github.com/hirasso/scrollmirror#usage-example

The CodePen example is also a good idea, especially for creating [minimal reproductions](https://en.wikipedia.org/wiki/Minimal_reproducible_example). I'll take care of this sometime soon.

**Comment by hirasso** [comment]
...also added a minimal example from CodePen to the README: https://codepen.io/rassohilber/pen/JjxwJpo

**Comment by bananenbiegerei** [comment]
Thanks @hirasso
